### ISSUE TITLE
Embed don't work anymore

### ISSUE THREAD

**Issue by CesiumCs** [moobcraft/neon#3]
thought it worked before but i guess it doesnt now
when running n!info:
```
(node:17825) UnhandledPromiseRejectionWarning: TypeError: fields.flat is not a function
    at Function.normalizeFields (/home/christian/neon/node_modules/discord.js/src/structures/MessageEmbed.js:450:8)
    at MessageEmbed.setup (/home/christian/neon/node_modules/discord.js/src/structures/MessageEmbed.js:78:91)
    at new MessageEmbed (/home/christian/neon/node_modules/discord.js/src/structures/MessageEmbed.js:18:10)
    at embedLikes.map.e (/home/christian/neon/node_modules/discord.js/src/structures/APIMessage.js:166:40)
    at Array.map (<anonymous>)
    at APIMessage.resolveData (/home/christian/neon/node_modules/discord.js/src/structures/APIMessage.js:166:31)
    at TextChannel.send (/home/christian/neon/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:166:62)
    at Object.exports.run (/home/christian/neon/commands/info.js:10:19)
    at module.exports (/home/christian/neon/events/message.js:24:7)
    at Client.emit (events.js:198:13)
(node:17825) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17825) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by CesiumCs** [comment]
fixed by commit https://github.com/moobcraft/neon/commit/12032fafc7ebda5775ad4dc19b23d14a14a61c42
